- name: Build MAX AI EXE
  run: npm run build


- name: Find EXE
  shell: bash
  run: |
    echo "Searching EXE..."
    find . -name "*.exe"


- name: Create Release and Upload EXE
  uses: softprops/action-gh-release@v2
  with:
    tag_name: v${{ steps.version.outputs.version }}
    name: MAX AI v${{ steps.version.outputs.version }}
    generate_release_notes: true
    files: |
      **/*.exe

  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
