name: MAX AI Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:

    runs-on: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install Packages
        run: npm install


      - name: Build MAX AI EXE
        run: npm run build


      - name: Find EXE File
        shell: powershell
        run: |
          Get-ChildItem -Path . -Filter *.exe -Recurse


      - name: Create MAX AI Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: MAX AI v${{ github.run_number }}
          generate_release_notes: true
          files: |
            **/*.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
